# Generated by go2rpm 1.11.1
%bcond_without check

# https://github.com/junegunn/fzf
%global goipath         github.com/junegunn/fzf
Version:                0.52.1
%global tag             %{version}

%gometa -L -f

%global common_description %{expand:
:cherry_blossom: A command-line fuzzy finder.}

%global golicenses      LICENSE src/LICENSE
%global godocs          doc ADVANCED.md BUILD.md CHANGELOG.md README-VIM.md\\\
                        README.md

Name:           fzf
Release:        %autorelease
Summary:        :cherry_blossom: A command-line fuzzy finder

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/fzf %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE src/LICENSE
%doc doc ADVANCED.md BUILD.md CHANGELOG.md README-VIM.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
