# Generated by go2rpm 1.11.1
%bcond_without check

# https://github.com/charlievieth/fastwalk
%global goipath         github.com/charlievieth/fastwalk
Version:                1.0.8

%gometa -L -f

%global common_description %{expand:
Fast directory traversal for Golang.}

%global golicenses      LICENSE go.LICENSE
%global godocs          examples README.md

Name:           golang-github-charlievieth-fastwalk
Release:        %autorelease
Summary:        Fast directory traversal for Golang

License:        BSD-3-Clause AND MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in scripts; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE go.LICENSE
%doc examples README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
