on:
  # Run on commit
  push:
  # Zen tends to update a lot, so run this once an hour
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"

      - name: update zen version
        run: |
          # Copr doesn't like using dashes for the version, so we have to manually change it to something it likes but keep it the same for
          # the source repo.
          RELEASES=$(curl -s https://api.github.com/repos/zen-browser/desktop/releases)
          ZEN_VER=$(echo $RELEASES | jq -r 'first(.[].tag_name | select(test("^[0-9]")))')
          ZEN_VER_SPEC=$(echo $ZEN_VER | sed 's@-@.@g')
          sed -i '0,/Version:.*/s//Version:            '$ZEN_VER_SPEC'/' /home/runner/work/copr/copr/zen-browser/zen-browser.spec
          sed -i '0,/Version:.*/s//Version:            '$ZEN_VER_SPEC'/' /home/runner/work/copr/copr/zen-browser/zen-browser-avx2.spec
          sed -i 's@https://github.com/zen-browser/desktop/releases/download/.*@https://github.com/zen-browser/desktop/releases/download/'$ZEN_VER'/zen.linux-generic.tar.bz2@g' /home/runner/work/copr/copr/zen-browser/zen-browser.spec
          sed -i 's@https://github.com/zen-browser/desktop/releases/download/.*@https://github.com/zen-browser/desktop/releases/download/'$ZEN_VER'/zen.linux-specific.tar.bz2@g' /home/runner/work/copr/copr/zen-browser/zen-browser-avx2.spec

          ZEN_TWILIGHT_VER=$(echo $RELEASES | jq -r '.[] | select(.tag_name == "twilight") | .name' | sed -E 's/.* - ([0-9]+(\.[0-9]+)*(-[a-zA-Z0-9\.]+)?) .*/\1/')
          ZEN_TWILIGHT_VER_SPEC=$(echo $ZEN_TWILIGHT_VER | sed 's@-@.@g')
          sed -i '0,/Version:.*/s//Version:            '$ZEN_TWILIGHT_VER_SPEC'/' /home/runner/work/copr/copr/zen-browser/zen-twilight.spec
          sed -i '0,/Version:.*/s//Version:            '$ZEN_TWILIGHT_VER_SPEC'/' /home/runner/work/copr/copr/zen-browser/zen-twilight-avx2.spec

          # TODO: reset release to 1

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(zen-browser): update version"
