on:
  # Run on commit
  push:
  # Zen tends to update a lot, so run this once an hour
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"

      - name: update zen version
        run: |
          reset_release_if_version_changed() {
            SPEC_FILE=$1
            NEW_VERSION=$2
            OLD_VERSION=$(grep "^Version:" $SPEC_FILE | awk '{print $2}')
            echo old $OLD_VERSION new $NEW_VERSION spec $SPEC_FILE
            if [[ "$OLD_VERSION" != "$NEW_VERSION" ]]; then
              sed -i -e '0,/Version:.*/s//Version:            '$NEW_VERSION'/' -e '0,/Release:.*/s//Release:            1%{?dist}/' $SPEC_FILE
            fi
          }

          # Get the latest version from the GitHub releases
          curl -s https://api.github.com/repos/zen-browser/desktop/releases > releases.txt

          # Copr doesn't like using dashes for the version, so we have to manually change it to something it likes but keep it the same for
          # the source repo.
          ZEN_VER=$(jq -r 'first(.[].tag_name | select(test("^[0-9]")))' releases.txt)
          ZEN_VER_SPEC=$(echo $ZEN_VER | sed 's@-@.@g')
          echo zen $ZEN_VER $ZEN_VER_SPEC

          # Update zen-browser.spec
          reset_release_if_version_changed "/home/runner/work/copr/copr/zen-browser/zen-browser.spec" $ZEN_VER_SPEC
          # Update the source URL
          sed -i 's@https://github.com/zen-browser/desktop/releases/download/.*@https://github.com/zen-browser/desktop/releases/download/'$ZEN_VER'/zen.linux-generic.tar.bz2@g' /home/runner/work/copr/copr/zen-browser/zen-browser.spec

          # Update zen-twilight.spec
          ZEN_TWILIGHT_VER=$(jq -r '.[] | select(.tag_name == "twilight") | .name' releases.txt | sed -E 's/.* - ([0-9]+(\.[0-9]+)*(-[a-zA-Z0-9\.]+)?) .*/\1/')
          ZEN_TWILIGHT_VER_SPEC=$(echo $ZEN_TWILIGHT_VER | sed 's@-@.@g')
          echo twilight $ZEN_TWILIGHT_VER $ZEN_TWILIGHT_VER_SPEC
          reset_release_if_version_changed "/home/runner/work/copr/copr/zen-browser/zen-twilight.spec" $ZEN_TWILIGHT_VER_SPEC

          rm releases.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(zen-browser): update version"
