on:
  # Run on commit
  push:
  # Zen tends to update a lot, so run this once an hour
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"

      - name: update zen version
        run: |
          update_spec_version() {
            SPEC_FILE=$1
            # Copr doesn't like using dashes for the version, so we have to manually change it to something it likes but keep it the same for
            # the source repo.
            NEW_VERSION=$(echo "$2" | sed 's/-/./g')
            OLD_VERSION=$(grep "^Version:" $SPEC_FILE | awk '{print $2}')
            if [[ "$OLD_VERSION" != "$NEW_VERSION" ]]; then
              echo old $OLD_VERSION new $NEW_VERSION spec $SPEC_FILE
              sed -i -e '0,/Version:.*/s//Version:            '$NEW_VERSION'/' -e '0,/Release:.*/s//Release:            1%{?dist}/' $SPEC_FILE
            fi
          }

          # Get the latest version from the GitHub releases
          RELEASES=$(curl -s https://api.github.com/repos/zen-browser/desktop/releases)

          # Update zen-browser.spec
          ZEN_VER=$(echo "$RELEASES" | jq -r 'first(.[].tag_name | select(test("^[0-9]")))')
          echo zen $ZEN_VER
          update_spec_version "/home/runner/work/copr/copr/zen-browser/zen-browser.spec" $ZEN_VER
          # Update the source URL
          sed -i 's@https://github.com/zen-browser/desktop/releases/download/.*@https://github.com/zen-browser/desktop/releases/download/'$ZEN_VER'/zen.linux-x86_64.tar.bz2@g' /home/runner/work/copr/copr/zen-browser/zen-browser.spec

          # Update zen-twilight.spec
          ZEN_TWILIGHT_VER=$(echo "$RELEASES" | jq -r '.[] | select(.tag_name == "twilight") | .name' | grep -Eo '[0-9]+(\.[a-zA-Z0-9-]+)+')
          echo twilight $ZEN_TWILIGHT_VER
          update_spec_version "/home/runner/work/copr/copr/zen-browser/zen-twilight.spec" $ZEN_TWILIGHT_VER

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(zen-browser): update version"
